## Pytorch

PyTorch is a machine learning library based on the Torch library, used for applications such as computer vision and natural language processing...

In [1]:
import torch

torch.__version__

'2.5.1'

### Value types

- Scaler - single value
- Vector - array of value
- Matrix - 2D array
- Tensor -  3D or More Dimension

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
vector = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [4]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [5]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [11]:
def infoAboutValues(tensor):
    print("-"*40)
    print(tensor)
    print(f"Dimension is {tensor.ndim}")
    print(f"Shape is {tensor.shape}")
    print(f"Dimension is {tensor.dtype}")

infoAboutValues(scaler)
infoAboutValues(vector)
infoAboutValues(matrix)
infoAboutValues(tensor)

----------------------------------------
tensor(7)
Dimension is 0
Shape is torch.Size([])
Dimension is torch.int64
----------------------------------------
tensor([1, 2, 3, 4, 5])
Dimension is 1
Shape is torch.Size([5])
Dimension is torch.int64
----------------------------------------
tensor([[1, 2],
        [3, 4]])
Dimension is 2
Shape is torch.Size([2, 2])
Dimension is torch.int64
----------------------------------------
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension is 3
Shape is torch.Size([2, 2, 3])
Dimension is torch.int64


### Creating tensors
 - Random
 - Zeros and once
 - Range

In [12]:
random_tensor = torch.rand(size=(2,3,2))
random_tensor

tensor([[[0.6308, 0.2695],
         [0.8488, 0.3586],
         [0.6140, 0.7959]],

        [[0.4556, 0.7821],
         [0.9606, 0.1777],
         [0.9653, 0.0182]]])

In [ ]:
random_tensor = torch.randint(10, 30, size=[1,2, 2]) # low, high, size
random_tensor

tensor([[[10, 12],
         [17, 19]]])

In [22]:
zero_tensor = torch.zeros(size=[2,3])
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
one_tensor = torch.ones(size=[2,3])
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
similar_tensor = torch.rand_like(one_tensor) #ones_like, zeros_like, randint_like, full_like - are used to create similar flavour
similar_tensor

tensor([[0.2110, 0.9196, 0.1011],
        [0.4572, 0.6911, 0.9580]])

In [ ]:
range_tensor = torch.arange(10, 20, 2) # start, end, step
range_tensor

tensor([10, 12, 14, 16, 18])

In [ ]:
cuda_tensor = torch.tensor([1,2,3,4], dtype=torch.int64, device='cpu') # replace device with 'cuda' if needed
cuda_tensor

tensor([1, 2, 3, 4])

### Tensor operations

In [32]:
tensor_1 = torch.randint(8, 30, size=[5, 3])
tensor_2 = torch.randint(4, 9, size=[5, 3])

print(tensor_1)
print(tensor_2)

tensor([[27, 24, 24],
        [15, 11, 22],
        [ 8, 23, 29],
        [19,  9, 17],
        [ 9, 26, 14]])
tensor([[4, 4, 5],
        [4, 4, 7],
        [8, 5, 7],
        [8, 7, 4],
        [8, 5, 4]])


In [33]:
tensor_1 + tensor_2

tensor([[31, 28, 29],
        [19, 15, 29],
        [16, 28, 36],
        [27, 16, 21],
        [17, 31, 18]])

In [34]:
tensor_1 + 4

tensor([[31, 28, 28],
        [19, 15, 26],
        [12, 27, 33],
        [23, 13, 21],
        [13, 30, 18]])

In [36]:
tensor_2 - 3

tensor([[1, 1, 2],
        [1, 1, 4],
        [5, 2, 4],
        [5, 4, 1],
        [5, 2, 1]])

In [37]:
tensor_1 - tensor_2

tensor([[23, 20, 19],
        [11,  7, 15],
        [ 0, 18, 22],
        [11,  2, 13],
        [ 1, 21, 10]])

In [39]:
# This is performed on element wise not the real matrix multiplication
tensor_1 * tensor_2

tensor([[108,  96, 120],
        [ 60,  44, 154],
        [ 64, 115, 203],
        [152,  63,  68],
        [ 72, 130,  56]])

In [42]:
# Matrix multiplication - > Real one 
torch.matmul(tensor_1, tensor_2.T)    # tensor_2.T -> is the transpose of tensor_2

tensor([[324, 372, 504, 480, 432],
        [214, 258, 329, 285, 263],
        [269, 327, 382, 341, 295],
        [197, 231, 316, 283, 265],
        [210, 238, 300, 310, 258]])

> Make sure for matrix multiplication column of 1st matrix and row of 2nd matrix should be `equal`

In [45]:
tensor_1 @ tensor_2.T # this is similar to matmul
# torch.mm is also same

tensor([[324, 372, 504, 480, 432],
        [214, 258, 329, 285, 263],
        [269, 327, 382, 341, 295],
        [197, 231, 316, 283, 265],
        [210, 238, 300, 310, 258]])

### Aggregation

In [47]:
tensor_1

tensor([[27, 24, 24],
        [15, 11, 22],
        [ 8, 23, 29],
        [19,  9, 17],
        [ 9, 26, 14]])

In [46]:
tensor_1.min()

tensor(8)

In [48]:
tensor_1.max()

tensor(29)

In [51]:
tensor_1.type(torch.float16).mean()

tensor(18.4688, dtype=torch.float16)

In [52]:
tensor_1.sum()

tensor(277)

In [ ]:
tensor_1.argmax() # it gives index of squeezed array

tensor(8)

In [60]:
tensor_1.argmin() # it gives index of squeezed array

tensor(6)

### Reshape the tensor