## Pytorch

PyTorch is a machine learning library based on the Torch library, used for applications such as computer vision and natural language processing...

In [1]:
import torch

torch.__version__

'2.5.1'

### Value types

- Scaler - single value
- Vector - array of value
- Matrix - 2D array
- Tensor -  3D or More Dimension

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
vector = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [4]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [5]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [11]:
def infoAboutValues(tensor):
    print("-"*40)
    print(tensor)
    print(f"Dimension is {tensor.ndim}")
    print(f"Shape is {tensor.shape}")
    print(f"Dimension is {tensor.dtype}")

infoAboutValues(scaler)
infoAboutValues(vector)
infoAboutValues(matrix)
infoAboutValues(tensor)

----------------------------------------
tensor(7)
Dimension is 0
Shape is torch.Size([])
Dimension is torch.int64
----------------------------------------
tensor([1, 2, 3, 4, 5])
Dimension is 1
Shape is torch.Size([5])
Dimension is torch.int64
----------------------------------------
tensor([[1, 2],
        [3, 4]])
Dimension is 2
Shape is torch.Size([2, 2])
Dimension is torch.int64
----------------------------------------
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension is 3
Shape is torch.Size([2, 2, 3])
Dimension is torch.int64


### Creating tensors
 - Random
 - Zeros and once
 - Range

In [12]:
random_tensor = torch.rand(size=(2,3,2))
random_tensor

tensor([[[0.6308, 0.2695],
         [0.8488, 0.3586],
         [0.6140, 0.7959]],

        [[0.4556, 0.7821],
         [0.9606, 0.1777],
         [0.9653, 0.0182]]])

In [ ]:
random_tensor = torch.randint(10, 30, size=[1,2, 2]) # low, high, size
random_tensor

tensor([[[10, 12],
         [17, 19]]])

In [22]:
zero_tensor = torch.zeros(size=[2,3])
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
one_tensor = torch.ones(size=[2,3])
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
similar_tensor = torch.rand_like(one_tensor) #ones_like, zeros_like, randint_like, full_like - are used to create similar flavour
similar_tensor

tensor([[0.2110, 0.9196, 0.1011],
        [0.4572, 0.6911, 0.9580]])

In [ ]:
range_tensor = torch.arange(10, 20, 2) # start, end, step
range_tensor

tensor([10, 12, 14, 16, 18])

In [ ]:
cuda_tensor = torch.tensor([1,2,3,4], dtype=torch.int64, device='cpu') # replace device with 'cuda' if needed
cuda_tensor

tensor([1, 2, 3, 4])

### Tensor operations